// Fun facts for the aircraft types that turn up around Ottawa (YOW).
// Source of record is data/ottawa_aircraft_fun_facts.xlsx; this file is
// generated from it. Keyed by ICAO type designator (Contact.enrichment.icaoType).

export interface AircraftFacts {
  /** ICAO type designator, e.g. "BCS3". */
  icao: string;
  manufacturer: string;
  /** Common name, e.g. "A220-300". */
  name: string;
  category: string;
  /** Operators seen with this type at YOW. */
  operators: string;
  /** Year entered service (may carry a parenthetical). */
  service: string;
  fact1: string;
  fact2: string;
  /** Nickname or spotting note; may be empty. */
  note: string;
}

const FACTS: AircraftFacts[] = [
  {
    icao: "A320",
    manufacturer: "Airbus",
    name: "A320",
    category: "Narrowbody Jet",
    operators: "Air Canada, Air Canada Rouge, WestJet",
    service: "1988",
    fact1: "The A320 was the first airliner ever built with full digital fly-by-wire controls, replacing mechanical cables with electronic signals.",
    fact2: "Over 11,000 A320-family jets have been built, making it one of the two best-selling airliner families in history (neck-and-neck with the 737).",
    note: "Family also includes the A319 and A321",
  },
  {
    icao: "A321",
    manufacturer: "Airbus",
    name: "A321 / A321neo",
    category: "Narrowbody Jet",
    operators: "Air Canada, WestJet",
    service: "1994 (A321neo: 2017)",
    fact1: "The A321neo (\"new engine option\") burns about 20% less fuel per seat than the original A321 thanks to new engines and wingtip sharklets.",
    fact2: "It's the longest member of the A320 family, stretched nearly 7 metres longer than the base A320.",
    note: "\"neo\" jets are easy to spot by their curved wingtip sharklets",
  },
  {
    icao: "A319",
    manufacturer: "Airbus",
    name: "A319",
    category: "Narrowbody Jet",
    operators: "Air Canada",
    service: "1996",
    fact1: "The A319 is the shortest of the classic A320 family and is popular for shorter, less-busy routes exactly like Ottawa's regional network.",
    fact2: "A319s were once used as executive VIP jets (ACJ319) for heads of state because their range with a light passenger load is huge.",
    note: "",
  },
  {
    icao: "BCS3",
    manufacturer: "Airbus",
    name: "A220-300",
    category: "Narrowbody Jet",
    operators: "Air Canada",
    service: "2016 (as CSeries)",
    fact1: "The A220 was originally designed and built entirely in Canada by Bombardier as the \"CSeries\" before Airbus took a majority stake in 2018.",
    fact2: "It's assembled in Mirabel, Quebec — meaning the plane flying over Ottawa may have been built just down the road.",
    note: "Started life as the Bombardier CS300",
  },
  {
    icao: "B738",
    manufacturer: "Boeing",
    name: "737-800",
    category: "Narrowbody Jet",
    operators: "WestJet, Air Canada",
    service: "1998",
    fact1: "The 737-800 is part of the best-selling \"Next Generation\" 737 family and remains the backbone of WestJet's entire fleet, which absorbed Sunwing's leisure network in 2025.",
    fact2: "A 737 has taken off or landed somewhere in the world roughly every 1.5 seconds on average — it's the most-produced Western jetliner ever.",
    note: "",
  },
  {
    icao: "B38M",
    manufacturer: "Boeing",
    name: "737 MAX 8",
    category: "Narrowbody Jet",
    operators: "WestJet, Flair Airlines",
    service: "2017",
    fact1: "The MAX's larger, more fuel-efficient engines sit further forward and higher on the wing than older 737s, giving it a distinctive look.",
    fact2: "Split-tip winglets (nicknamed \"scimitar\" winglets) reduce drag and are one of the easiest ways to tell a MAX apart from an older 737.",
    note: "",
  },
  {
    icao: "B788",
    manufacturer: "Boeing",
    name: "787-8 Dreamliner",
    category: "Widebody Jet",
    operators: "Air Canada",
    service: "2011",
    fact1: "The 787 was the first airliner built mostly from carbon-fibre composite instead of aluminum, letting cabins be pressurized to a lower, more comfortable altitude.",
    fact2: "Its windows are the largest of any commercial jet and dim electronically instead of using pull-down shades.",
    note: "Occasionally swapped onto Ottawa's transatlantic routes",
  },
  {
    icao: "B77W",
    manufacturer: "Boeing",
    name: "777-300ER",
    category: "Widebody Jet",
    operators: "Air France (seasonal), occasional Air Canada",
    service: "2004",
    fact1: "The 777's wingtips are so long and flexible that in testing they were bent upward more than 7 metres before the wing failed.",
    fact2: "It's the largest twin-engine jet ever built, and each of its GE90 engines is wide enough to fit a 737 fuselage through the intake.",
    note: "",
  },
  {
    icao: "B763",
    manufacturer: "Boeing",
    name: "767-300",
    category: "Widebody / Freighter",
    operators: "Cargojet, occasional Air Canada Rouge",
    service: "1986",
    fact1: "Retired passenger 767s are widely converted into freighters, and Cargojet's overnight network keeps several flying nightly out of Ottawa.",
    fact2: "The 767 was the first Boeing widebody designed from the outset for two-pilot crews instead of three.",
    note: "",
  },
  {
    icao: "B752",
    manufacturer: "Boeing",
    name: "757-200",
    category: "Narrowbody / Freighter",
    operators: "Cargojet, FedEx",
    service: "1983",
    fact1: "The 757 has the best power-to-weight ratio of any Boeing airliner, giving it famously strong takeoff performance out of shorter runways.",
    fact2: "Production ended in 2004, but so many were converted to freighters that it remains a staple of overnight cargo networks today.",
    note: "",
  },
  {
    icao: "E75L",
    manufacturer: "Embraer",
    name: "E175",
    category: "Regional Jet",
    operators: "Air Canada Express, United Express",
    service: "2005",
    fact1: "The E175 seats around 76 passengers and is the sweet spot size for feeder routes into a hub like Ottawa.",
    fact2: "Embraer's E-Jets were the first regional jets designed with a wider, more comfortable 2-2 cabin instead of the cramped 1-2 layout common on older regional jets.",
    note: "",
  },
  {
    icao: "E295",
    manufacturer: "Embraer",
    name: "E195-E2",
    category: "Narrowbody Jet",
    operators: "Porter Airlines",
    service: "2019",
    fact1: "The E195-E2 is Porter Airlines' primary jet for its expansion beyond Toronto Billy Bishop, and Porter was a global launch customer for the type.",
    fact2: "It's the quietest commercial jet in its class, certified under strict noise rules — handy for an airline that also flies out of a downtown airport.",
    note: "",
  },
  {
    icao: "CRJ9",
    manufacturer: "Bombardier",
    name: "CRJ900",
    category: "Regional Jet",
    operators: "Air Canada Express (Jazz)",
    service: "2003",
    fact1: "The CRJ family traces its roots to the Canadair Challenger business jet — the CRJ900's fuselage was literally stretched from a corporate jet design.",
    fact2: "Jazz Aviation, based in Halifax, operates the largest regional jet fleet in Canada, much of it feeding Air Canada's Ottawa flights.",
    note: "",
  },
  {
    icao: "CRJ2",
    manufacturer: "Bombardier",
    name: "CRJ200",
    category: "Regional Jet",
    operators: "Air Canada Express, PAL Airlines",
    service: "1992",
    fact1: "The CRJ200 was the aircraft that kicked off the modern regional-jet boom in North America in the 1990s.",
    fact2: "It cruises at the same altitude as many mainline jets, letting it fly above weather that keeps smaller turboprops grounded.",
    note: "",
  },
  {
    icao: "DH8D",
    manufacturer: "De Havilland Canada",
    name: "Dash 8-400 (Q400)",
    category: "Turboprop",
    operators: "Porter Airlines, Air Canada Express",
    service: "2000",
    fact1: "The Q400 is built in Toronto and is one of the fastest turboprops flying, cruising nearly as fast as some regional jets.",
    fact2: "Porter Airlines built its entire original identity around the Q400 and its signature tartan livery before adding jets in 2022.",
    note: "\"Q\" stood for \"quiet\" — active noise-cancelling technology in the cabin",
  },
  {
    icao: "DH8C",
    manufacturer: "De Havilland Canada",
    name: "Dash 8-300",
    category: "Turboprop",
    operators: "PAL Airlines, Air Inuit",
    service: "1989",
    fact1: "The Dash 8 family was originally developed by de Havilland Canada in Toronto and is still in production there today under De Havilland Canada.",
    fact2: "Its high wing and large propellers give it excellent short-field performance, useful for smaller northern and regional airports.",
    note: "",
  },
  {
    icao: "AT72",
    manufacturer: "ATR",
    name: "ATR 72",
    category: "Turboprop",
    operators: "Air Inuit, charter operators",
    service: "1988",
    fact1: "ATR is a joint venture between France's Airbus-linked Aerospatiale heritage and Italy's Leonardo, still building turboprops in Toulouse today.",
    fact2: "Its low wing keeps the cabin closer to the ground, so it doesn't need boarding stairs on shorter turnarounds.",
    note: "",
  },
  {
    icao: "DHC6",
    manufacturer: "De Havilland Canada",
    name: "DHC-6 Twin Otter",
    category: "Turboprop / Bush Plane",
    operators: "Air Inuit, survey/geophysics operators",
    service: "1965",
    fact1: "The Twin Otter can take off in under 300 metres and is still in production today (by Viking Air) because nothing else matches its rugged short-field ability.",
    fact2: "It's the aircraft of choice for Arctic and Antarctic research stations worldwide, including landing on skis and floats.",
    note: "",
  },
  {
    icao: "C208",
    manufacturer: "Cessna",
    name: "208 Caravan",
    category: "Utility Turboprop",
    operators: "Sanders Geophysics, small cargo/survey operators",
    service: "1984",
    fact1: "The Caravan was originally developed with FedEx as a launch customer for feeder cargo routes, and small Caravans still fly overnight parcels today.",
    fact2: "It can be fitted with wheels, skis, or floats, making it one of the most versatile single-engine aircraft ever built.",
    note: "",
  },
  {
    icao: "PC12",
    manufacturer: "Pilatus",
    name: "PC-12",
    category: "Turboprop",
    operators: "RCMP",
    service: "1994",
    fact1: "The PC-12 has a cabin large enough to convert into an air ambulance layout, and it's a favourite of police and medevac operators across Canada.",
    fact2: "Swiss-built Pilatus aircraft are known for exceptional short and rough-field performance, useful for reaching remote communities.",
    note: "",
  },
  {
    icao: "C560",
    manufacturer: "Cessna",
    name: "Citation V / Encore",
    category: "Business Jet",
    operators: "Transport Canada",
    service: "1989",
    fact1: "Transport Canada operates Citation jets for aviation inspections and calibrating the navigation aids at airports across the country.",
    fact2: "The Citation family is the best-selling business jet line in history, with well over 7,000 delivered.",
    note: "",
  },
  {
    icao: "GLEX",
    manufacturer: "Bombardier",
    name: "Global Express",
    category: "Business Jet",
    operators: "Corporate/charter operators (AirSprint and others)",
    service: "1998",
    fact1: "The Global Express was designed to fly nonstop from North America to Asia or Europe, and it set multiple round-the-world speed records after entering service.",
    fact2: "It was developed in Montreal using swept-wing technology borrowed from Bombardier's regional jet programs.",
    note: "",
  },
  {
    icao: "CL60",
    manufacturer: "Bombardier",
    name: "Challenger 604/605/650",
    category: "Business Jet",
    operators: "Corporate operators, RCAF (as CC-144)",
    service: "1996 (604)",
    fact1: "The Challenger was Bombardier's very first clean-sheet aircraft design, launched back in 1976, and its wide cabin cross-section was later reused for the CRJ regional jet.",
    fact2: "The RCAF's Challengers (CC-144) fly VIP transport for the Governor General, Prime Minister, and cabinet ministers out of Ottawa.",
    note: "",
  },
  {
    icao: "A310",
    manufacturer: "Airbus",
    name: "CC-150 Polaris (A310)",
    category: "Government / Strategic Transport",
    operators: "Royal Canadian Air Force",
    service: "1985 (A310); 1992 (RCAF conversion)",
    fact1: "Canada's five CC-150 Polaris jets are converted ex-airline A310s, some originally flown by Wardair and Canadian Airlines before joining the military.",
    fact2: "They serve as VIP transport for the Prime Minister and Governor General as well as strategic troop and cargo airlift, and can be fitted for air-to-air refuelling.",
    note: "Being phased out as the CC-330 Husky arrives",
  },
  {
    icao: "A332",
    manufacturer: "Airbus",
    name: "CC-330 Husky (A330 MRTT)",
    category: "Government / Tanker",
    operators: "Royal Canadian Air Force",
    service: "2025 (Canadian delivery)",
    fact1: "The CC-330 Husky is Canada's newest military aircraft type, a converted Airbus A330 multi-role tanker that can refuel fighter jets in mid-air.",
    fact2: "It's named \"Husky\" after the sled dog, continuing the RCAF tradition of naming heavy transport aircraft after Canadian working dogs.",
    note: "Replacing the CC-150 Polaris fleet",
  },
  {
    icao: "C130",
    manufacturer: "Lockheed Martin",
    name: "CC-130J Hercules",
    category: "Military Transport",
    operators: "Royal Canadian Air Force",
    service: "1999 (J model); 1960 (original Hercules)",
    fact1: "The Hercules has been in continuous production longer than any other military aircraft in history — over 65 years and counting.",
    fact2: "RCAF Hercules based out of the Ottawa area fly everything from Arctic resupply to search-and-rescue and disaster relief missions.",
    note: "",
  },
  {
    icao: "C17",
    manufacturer: "Boeing",
    name: "CC-177 Globemaster III",
    category: "Military Transport",
    operators: "Royal Canadian Air Force",
    service: "1995 (C-17); 2007 (RCAF)",
    fact1: "Canada's four Globemasters can carry a main battle tank and are among the largest aircraft to regularly use Ottawa's airport.",
    fact2: "The C-17 can land and take off from runways as short as about 1,000 metres, far shorter than a typical airliner needs.",
    note: "",
  },
  {
    icao: "ALJT",
    manufacturer: "Dassault-Dornier",
    name: "Alpha Jet",
    category: "Research / Chase Aircraft",
    operators: "National Research Council of Canada",
    service: "1978",
    fact1: "The NRC's Alpha Jets are used as chase planes to film and monitor experimental flight tests in real time from the air.",
    fact2: "The Alpha Jet was originally a joint French-German military trainer before a handful found second careers in Canadian flight research.",
    note: "",
  },
  {
    icao: "F20",
    manufacturer: "Dassault",
    name: "Falcon 20",
    category: "Research Aircraft",
    operators: "National Research Council of Canada",
    service: "1965",
    fact1: "NRC's Falcon 20 has flown atmospheric and icing research missions for decades, including flying directly into storm clouds to study ice buildup on wings.",
    fact2: "The Falcon 20 was Dassault's first business jet and helped launch the entire modern corporate jet industry.",
    note: "",
  },
  {
    icao: "CV58",
    manufacturer: "Convair",
    name: "CV-580",
    category: "Historic Research Aircraft",
    operators: "National Research Council of Canada",
    service: "1947 (as CV-240); 1960 (580 conversion)",
    fact1: "NRC's CV-580 has been used for decades of Canadian cloud-physics and icing research, flying into freezing rain to measure how ice forms on aircraft.",
    fact2: "It started life in the 1940s as a piston-engine Convair 240 airliner before being re-engined with turboprops in the 1950s-60s conversion program.",
    note: "",
  },
  {
    icao: "T-33",
    manufacturer: "Lockheed",
    name: "T-33 Shooting Star",
    category: "Historic Jet",
    operators: "National Research Council of Canada (heritage)",
    service: "1948",
    fact1: "The T-33 was North America's first mass-produced jet trainer, and Canadian-built versions (by Canadair) trained generations of RCAF pilots.",
    fact2: "NRC kept T-33s flying long after most air forces retired theirs, using them for decades of airborne research work.",
    note: "",
  },
  {
    icao: "E545",
    manufacturer: "Embraer",
    name: "Legacy 450",
    category: "Business Jet",
    operators: "AirSprint (fractional ownership)",
    service: "2015",
    fact1: "The Legacy 450 shares its wing design with Embraer's larger commercial jets, giving it an unusually smooth ride for its size.",
    fact2: "AirSprint, a Canadian fractional-ownership company, bases part of its private jet fleet in Ottawa for cross-Canada business travel.",
    note: "",
  },
  {
    icao: "C25B",
    manufacturer: "Cessna",
    name: "Citation CJ2/CJ3",
    category: "Business Jet",
    operators: "AirSprint and other charter operators",
    service: "2000 (CJ2)",
    fact1: "The CJ series is designed to be flown by a single pilot, keeping it popular with owner-operators and small charter fleets.",
    fact2: "It can use shorter runways than most jets its size, opening up smaller regional airports for private travel.",
    note: "",
  },
  {
    icao: "LJ60",
    manufacturer: "Bombardier (Learjet)",
    name: "Learjet 60",
    category: "Business Jet",
    operators: "Charter operators",
    service: "1993",
    fact1: "Learjet essentially invented the modern light business jet category in the 1960s, and \"Lear jet\" became a generic household term for any private jet.",
    fact2: "The Learjet 60 was one of the last all-new Learjet designs before Bombardier eventually wound the historic brand down in 2021.",
    note: "",
  },
  {
    icao: "A21N",
    manufacturer: "Airbus",
    name: "A321neo",
    category: "Narrowbody Jet",
    operators: "Air Canada",
    service: "2017",
    fact1: "Air Canada uses long-range A321neo/XLR variants on thinner transatlantic routes, something no single-aisle jet could do economically a decade ago.",
    fact2: "The A321XLR carries extra fuel in a permanent tank built into the rear cargo hold instead of bulky removable tanks.",
    note: "\"XLR\" = Xtra Long Range",
  },
  {
    icao: "A333",
    manufacturer: "Airbus",
    name: "A330-300",
    category: "Widebody Jet",
    operators: "Air Transat (seasonal)",
    service: "1993",
    fact1: "Air Transat is Canada's largest A330 operator and uses them on Ottawa's seasonal nonstop flights to Europe and sun destinations.",
    fact2: "The A330 shares a cockpit design and type rating with the four-engine A340, so pilots can fly both with minimal extra training.",
    note: "",
  },
  {
    icao: "B737",
    manufacturer: "Boeing",
    name: "737-700",
    category: "Narrowbody Jet",
    operators: "WestJet",
    service: "1997",
    fact1: "The 737-700 was WestJet's original workhorse when the airline launched in 1996, flying its very first routes.",
    fact2: "It shares its fuselage length with the older 737-300 but uses the more modern, more efficient Next Generation wing and engines.",
    note: "",
  },
  {
    icao: "E190",
    manufacturer: "Embraer",
    name: "E190",
    category: "Regional Jet",
    operators: "Air Canada (historic, retired 2019)",
    service: "2004",
    fact1: "Air Canada's E190s were nicknamed the \"Jazz-buster\" fleet internally since they let the airline fly mainline-branded service on thinner routes.",
    fact2: "The E190 was the first regional jet with a true 2-2 seating layout and no middle seat, a first for aircraft under 100 seats.",
    note: "Retired from Air Canada's fleet, but still seen visiting as charters",
  },
  {
    icao: "CRJ7",
    manufacturer: "Bombardier",
    name: "CRJ700",
    category: "Regional Jet",
    operators: "Air Canada Express (Jazz)",
    service: "2001",
    fact1: "The CRJ700 was stretched from the CRJ200 to add roughly 20 more seats, aimed directly at competing with Embraer's E-Jets.",
    fact2: "It was the first Bombardier regional jet built with a supercritical wing designed specifically for the larger airframe rather than reused from the original CRJ.",
    note: "",
  },
  {
    icao: "B77L",
    manufacturer: "Boeing",
    name: "777-200LR",
    category: "Widebody Jet",
    operators: "Occasional charter/diversion",
    service: "2006",
    fact1: "The 777-200LR once set the record for the longest nonstop flight by a commercial airliner, flying Hong Kong to London the \"wrong way\" around the globe.",
    fact2: "\"LR\" stands for Longer Range — it carries extra fuel tanks in its cargo hold like some A321 variants.",
    note: "Rare visitor, usually only for special charters or diversions",
  },
  {
    icao: "BE35",
    manufacturer: "Beechcraft",
    name: "King Air 350",
    category: "Turboprop",
    operators: "Corporate charter, air ambulance",
    service: "1990",
    fact1: "The King Air family is the best-selling twin-turboprop business aircraft line in history, with well over 7,000 built since 1964.",
    fact2: "Pressurized cabins let King Airs cruise above most weather, a big reason they're a favourite for air ambulance operators across Canada.",
    note: "",
  },
  {
    icao: "C750",
    manufacturer: "Cessna",
    name: "Citation X",
    category: "Business Jet",
    operators: "Charter operators",
    service: "1996",
    fact1: "The Citation X was the fastest civilian aircraft in the world for years, cruising at Mach 0.92 — just a hair under the speed of sound.",
    fact2: "Its swept wing was borrowed and adapted from fighter-jet aerodynamic research to reach that speed efficiently.",
    note: "",
  },
  {
    icao: "C510",
    manufacturer: "Cessna",
    name: "Citation Mustang",
    category: "Very Light Jet",
    operators: "Owner-operator/charter",
    service: "2006",
    fact1: "The Mustang helped kick off the \"very light jet\" category, small enough to be flown single-pilot and priced within reach of many small businesses.",
    fact2: "It can be flown by pilots with relatively modest jet experience thanks to a simplified glass cockpit designed for owner-pilots.",
    note: "",
  },
  {
    icao: "C680",
    manufacturer: "Cessna",
    name: "Citation Sovereign",
    category: "Business Jet",
    operators: "Charter/corporate operators",
    service: "2004",
    fact1: "The Sovereign was designed with a wide cabin cross-section shared with Cessna's larger Citation X, giving it more headroom than most jets its size.",
    fact2: "It's popular with corporate flight departments for its combination of a transcontinental-length cabin and short-runway capability.",
    note: "",
  },
  {
    icao: "GLF4",
    manufacturer: "Gulfstream",
    name: "G450",
    category: "Business Jet",
    operators: "Corporate/charter operators",
    service: "2005",
    fact1: "Gulfstreams are a favourite of corporate flight departments and foreign government delegations, both common visitors during Ottawa's diplomatic and parliamentary events.",
    fact2: "The G450 can fly nonstop from Ottawa to nearly anywhere in Europe or South America without refuelling.",
    note: "",
  },
  {
    icao: "GLF5",
    manufacturer: "Gulfstream",
    name: "G550",
    category: "Business Jet",
    operators: "Corporate/charter, foreign government delegations",
    service: "2003",
    fact1: "The G550 has been used by NASA as a testbed and astronaut-training aircraft, alongside its usual role as a long-range executive jet.",
    fact2: "It held multiple round-the-world and city-pair speed records after entering service.",
    note: "",
  },
  {
    icao: "GLF6",
    manufacturer: "Gulfstream",
    name: "G650",
    category: "Business Jet",
    operators: "Corporate/charter operators",
    service: "2012",
    fact1: "The G650 was, at launch, the fastest and longest-range civilian jet in the world, capable of flying from Ottawa to Tokyo nonstop.",
    fact2: "Its cabin windows are the largest of any purpose-built business jet, nearly 40% bigger than on Gulfstream's previous models.",
    note: "",
  },
  {
    icao: "F900",
    manufacturer: "Dassault",
    name: "Falcon 900",
    category: "Business Jet",
    operators: "Corporate/charter, government delegations",
    service: "1986",
    fact1: "The Falcon 900 is one of the few business jets with three engines, a layout chosen to guarantee it could keep flying over oceans even after losing one engine.",
    fact2: "Dassault, its manufacturer, also builds the Rafale fighter jet — Falcon business jets borrow aerodynamic know-how from that military heritage.",
    note: "",
  },
  {
    icao: "F2TH",
    manufacturer: "Dassault",
    name: "Falcon 2000",
    category: "Business Jet",
    operators: "Corporate/charter operators",
    service: "1995",
    fact1: "The Falcon 2000 was designed as a twin-engine, lower-cost complement to the tri-jet Falcon 900, sized for medium-range corporate travel.",
    fact2: "Like all Falcons, it uses a fighter-jet-style wing designed for a smooth ride in rough air.",
    note: "",
  },
  {
    icao: "FA7X",
    manufacturer: "Dassault",
    name: "Falcon 7X",
    category: "Business Jet",
    operators: "Corporate/charter, government delegations",
    service: "2007",
    fact1: "The Falcon 7X was the first business jet with full digital fly-by-wire flight controls, technology borrowed directly from airliners and fighter jets.",
    fact2: "It has three engines like its Falcon 900 predecessor, giving it extra range and safety margin over long ocean crossings.",
    note: "",
  },
  {
    icao: "H25B",
    manufacturer: "Hawker",
    name: "800XP / 900XP",
    category: "Business Jet",
    operators: "Charter operators",
    service: "1995 (800XP)",
    fact1: "The Hawker family traces its roots all the way back to the 1960s de Havilland DH.125, making it one of the longest continuously-produced business jet designs.",
    fact2: "Its distinctive oval-cross-section fuselage was inherited from that 1960s design and remained largely unchanged for over 40 years of production.",
    note: "",
  },
  {
    icao: "LJ45",
    manufacturer: "Bombardier (Learjet)",
    name: "Learjet 45 / 75",
    category: "Business Jet",
    operators: "Charter operators",
    service: "1998",
    fact1: "The Learjet 45 was the first all-new Learjet design in decades and the last clean-sheet Learjet before the brand's retirement in 2021.",
    fact2: "Learjets are known for a distinctively fast, steep climb rate that pilots often describe as feeling like a fighter jet departure.",
    note: "",
  },
  {
    icao: "PC24",
    manufacturer: "Pilatus",
    name: "PC-24",
    category: "Business Jet",
    operators: "Corporate/charter operators",
    service: "2018",
    fact1: "The PC-24 is nicknamed the \"Super Versatile Jet\" because, unlike most business jets, it can operate from short, unpaved runways.",
    fact2: "It has a large cargo door that lets it double as a light freighter or air ambulance when the cabin is reconfigured.",
    note: "",
  },
  {
    icao: "GL7T",
    manufacturer: "Bombardier",
    name: "Global 7500",
    category: "Business Jet",
    operators: "Corporate/charter operators",
    service: "2012 (6000); 2018 (7500)",
    fact1: "The Global 7500 can fly nonstop from Ottawa to almost any city on Earth, with a range exceeding 14,000 km.",
    fact2: "It has four distinct living spaces in the cabin, more than any other purpose-built business jet when it launched.",
    note: "",
  },
  {
    icao: "A139",
    manufacturer: "Leonardo",
    name: "AW139",
    category: "Helicopter",
    operators: "Ornge air ambulance",
    service: "2003",
    fact1: "Ornge, Ontario's air ambulance service, flies AW139s in and out of The Ottawa Hospital's rooftop helipad on medevac missions around the clock.",
    fact2: "The AW139 was co-developed by Italy's Leonardo (then Agusta) and Bell of Canada/USA before the two companies later split the program.",
    note: "",
  },
  {
    icao: "B407",
    manufacturer: "Bell",
    name: "407",
    category: "Helicopter",
    operators: "Police, corporate, utility operators",
    service: "1995",
    fact1: "The Bell 407 replaced the classic Jet Ranger as the standard light helicopter for police, utility, and corporate flying across North America.",
    fact2: "Its four-blade rotor system was adapted from Bell's OH-58D Kiowa Warrior military scout helicopter.",
    note: "",
  },
  {
    icao: "EC35",
    manufacturer: "Airbus Helicopters",
    name: "H135",
    category: "Helicopter",
    operators: "Air ambulance, corporate operators",
    service: "1996",
    fact1: "The H135's fenestron (shrouded tail rotor) makes it noticeably quieter than helicopters with a conventional exposed tail rotor — a real advantage over hospitals and neighbourhoods.",
    fact2: "It's one of the most widely used twin-engine light helicopters for air ambulance work worldwide.",
    note: "",
  },
  {
    icao: "C172",
    manufacturer: "Cessna",
    name: "172 Skyhawk",
    category: "Trainer / GA",
    operators: "Flight schools (Ottawa Flying Club and others)",
    service: "1956",
    fact1: "The Cessna 172 is the most-produced aircraft in aviation history, with more than 44,000 built and still in production today.",
    fact2: "It's the aircraft most private pilots in Canada, including many now flying airliners, first learned to fly on.",
    note: "",
  },
  {
    icao: "PA28",
    manufacturer: "Piper",
    name: "PA-28 Cherokee / Warrior",
    category: "Trainer / GA",
    operators: "Flight schools",
    service: "1960",
    fact1: "The Cherokee's simple, low-wing, single-piece-wing design made it cheaper to build and maintain than many of its rivals, helping it become a flight-school staple worldwide.",
    fact2: "Over 90 versions of the PA-28 have been built since the 1960s, spanning trainers to fast cross-country touring aircraft.",
    note: "",
  },
  {
    icao: "DA40",
    manufacturer: "Diamond Aircraft",
    name: "DA40",
    category: "Trainer / GA",
    operators: "Flight schools",
    service: "1997",
    fact1: "Diamond's composite airframe construction (rather than traditional riveted aluminum) gives the DA40 a distinctively smooth, sleek shape for a training aircraft.",
    fact2: "It's built in London, Ontario, making it one of relatively few aircraft you might see flying over Ottawa that's fully Canadian-built.",
    note: "",
  },
  {
    icao: "DA42",
    manufacturer: "Diamond Aircraft",
    name: "DA42 Twin Star",
    category: "Trainer / GA",
    operators: "Flight schools (multi-engine training)",
    service: "2004",
    fact1: "The DA42 was one of the first light twins designed from scratch around efficient diesel/Jet-A-burning engines instead of traditional avgas piston engines.",
    fact2: "Like the DA40, it's built by Diamond Aircraft in London, Ontario.",
    note: "",
  },
  {
    icao: "SR22",
    manufacturer: "Cirrus",
    name: "SR22",
    category: "GA",
    operators: "Private owners",
    service: "2001",
    fact1: "Every Cirrus SR22 comes with a whole-airplane parachute system (CAPS) that can lower the entire aircraft safely to the ground in an emergency.",
    fact2: "It has been the best-selling piston aircraft in the world for most years since the early 2000s.",
    note: "",
  },
  {
    icao: "DHC2",
    manufacturer: "De Havilland Canada",
    name: "DHC-2 Beaver",
    category: "Bush Plane",
    operators: "Occasional visitor/historic operators",
    service: "1947",
    fact1: "The Beaver was built in Toronto and is considered one of the most important Canadian aircraft ever made, engineered specifically for bush flying on floats, wheels, or skis.",
    fact2: "The Canadian Engineering Centennial Board named the Beaver one of the top ten Canadian engineering achievements of the 20th century.",
    note: "Ottawa's Canada Aviation and Space Museum, just minutes from YOW, has an original on display",
  },
  {
    icao: "A124",
    manufacturer: "Antonov",
    name: "An-124 Ruslan",
    category: "Heavy Cargo (rare charter)",
    operators: "Occasional military/oversize-cargo charters",
    service: "1982",
    fact1: "The An-124 is one of the largest cargo aircraft ever built and is sometimes chartered by the Canadian government to move outsized military or disaster-relief equipment through Ottawa.",
    fact2: "Its cargo hold is tall and wide enough to swallow entire helicopters or armoured vehicles, loaded through a nose that swings open like a drawbridge.",
    note: "A rare, unmistakable visitor when it does appear",
  },
  {
    icao: "B744",
    manufacturer: "Boeing",
    name: "747-400 (Freighter)",
    category: "Heavy Cargo (rare charter)",
    operators: "Occasional cargo charter",
    service: "1989",
    fact1: "The 747's hump-backed profile exists because Boeing originally designed the cockpit to sit above a front-loading cargo door, expecting the jet to eventually become mostly a freighter.",
    fact2: "For over 35 years after its 1970 debut, the 747 held the title of the world's largest passenger aircraft.",
    note: "",
  },
  {
    icao: "CH146",
    manufacturer: "Bell",
    name: "CH-146 Griffon",
    category: "Military Helicopter",
    operators: "Royal Canadian Air Force (412 Transport Squadron, Ottawa)",
    service: "1995",
    fact1: "412 Transport Squadron is based right at Ottawa's airport and has flown VIP and utility helicopter support for the federal government since the 1990s.",
    fact2: "The Griffon is a militarized version of the civilian Bell 412, itself a twin-engine development of the classic Bell 212/UH-1 \"Huey\" family.",
    note: "Canada's most numerous military helicopter type",
  },
  {
    icao: "B412EP",
    manufacturer: "Bell",
    name: "412EP",
    category: "Helicopter",
    operators: "RCAF-linked and civil utility/VIP operators",
    service: "1994",
    fact1: "\"EP\" stands for Enhanced Performance — this variant added a better transmission and higher gross weight than the original Bell 412.",
    fact2: "Bell 412s are built with a four-blade, soft-in-plane rotor system that gives a notably smoother ride than the two-blade Huey it descended from.",
    note: "",
  },
  {
    icao: "B412EPI",
    manufacturer: "Bell",
    name: "412EPI",
    category: "Helicopter",
    operators: "RCAF-linked and civil utility/VIP operators",
    service: "2011",
    fact1: "The 412EPI updated the Bell 412 with a modern glass cockpit, part of the same upgrade philosophy Canada later applied to extend the CH-146 Griffon's service life.",
    fact2: "\"EPI\" (Enhanced Performance Improved) aircraft can often be told apart from older 412s by their flat-panel digital instrument displays visible through the windscreen.",
    note: "",
  },
  {
    icao: "B205",
    manufacturer: "Bell",
    name: "205A-1++",
    category: "Helicopter",
    operators: "Utility/forestry/fire-support operators",
    service: "1971",
    fact1: "The 205 is a civilian-certified descendant of the military UH-1 Huey, and the \"++\" upgrade package re-engines older airframes for hot-and-high performance decades after they were built.",
    fact2: "Huey-family helicopters like the 205 remain popular for firefighting and heavy-lift utility work because parts and expertise are still widely available.",
    note: "",
  },
  {
    icao: "B206",
    manufacturer: "Bell",
    name: "206 JetRanger / LongRanger",
    category: "Helicopter",
    operators: "Police, tour, utility, corporate operators",
    service: "1967",
    fact1: "The Bell 206 was originally a losing entrant in a U.S. Army scout-helicopter competition — Bell reworked it into a civilian model and it went on to outsell almost every other light helicopter in history.",
    fact2: "It's a longtime favourite for police air support, TV news, and sightseeing tours because of its low operating cost and excellent visibility bubble canopy.",
    note: "",
  },
  {
    icao: "B429",
    manufacturer: "Bell",
    name: "429 GlobalRanger",
    category: "Helicopter",
    operators: "Police, air ambulance, corporate operators",
    service: "2009",
    fact1: "The Bell 429 was the first helicopter type-certified for single-pilot IFR (instrument flight rules) operation with a full glass cockpit, letting crews fly safely at night and in poor weather.",
    fact2: "Its distinctive four-blade rotor and twin engines make it a common choice for police air-support units and air ambulance operators across Ontario.",
    note: "",
  },
  {
    icao: "CH47",
    manufacturer: "Boeing",
    name: "CH-147F Chinook",
    category: "Military Helicopter",
    operators: "Royal Canadian Air Force (450 Tactical Helicopter Squadron)",
    service: "2013 (Canadian F model)",
    fact1: "The tandem-rotor Chinook has no tail rotor at all — its two big rotors turn in opposite directions, cancelling out the torque a normal helicopter needs a tail rotor to counter.",
    fact2: "Canada's Chinooks are normally based in Petawawa but periodically visit Ottawa for military ceremonies, VIP support, and training moves.",
    note: "",
  },
  {
    icao: "UH60",
    manufacturer: "Sikorsky",
    name: "UH-60 Black Hawk",
    category: "Military Helicopter",
    operators: "Occasional visitor — foreign military/VIP escort",
    service: "1979",
    fact1: "Canada doesn't operate Black Hawks itself, so a UH-60 over Ottawa is most often part of a visiting U.S. military detachment supporting a high-profile government or presidential visit.",
    fact2: "The Black Hawk's airframe was designed to be survivable, with a crash-resistant structure and seats engineered to absorb impact energy in a hard landing.",
    note: "A rare, notable visitor — usually tied to a specific VIP event",
  },
  {
    icao: "AS350",
    manufacturer: "Airbus Helicopters (Eurocopter)",
    name: "AS350 B / \"Écureuil\"",
    category: "Helicopter",
    operators: "Police, media, tour, and utility operators",
    service: "1977",
    fact1: "The AS350 (\"Squirrel\" in English) holds the all-time helicopter altitude landing record after one was flown to the summit of Mount Everest in 2005.",
    fact2: "Its single Turbomeca engine and simple systems make it a favourite worldwide for police air-support, news, and aerial-survey work.",
    note: "",
  },
  {
    icao: "DH8A",
    manufacturer: "De Havilland Canada",
    name: "Dash 8-100 (Flight Inspection)",
    category: "Government / Calibration Aircraft",
    operators: "NAV CANADA",
    service: "1984",
    fact1: "NAV CANADA, the country's air navigation service provider, is headquartered in Ottawa and uses specially equipped aircraft to fly precise, repeated patterns that calibrate runway approach lights and navigation beacons at airports nationwide.",
    fact2: "If you ever see a plane over Ottawa flying oddly repetitive loops and step-climbs, there's a good chance it's not lost — it's a flight-inspection aircraft doing its job.",
    note: "",
  },
  {
    icao: "A359",
    manufacturer: "Airbus",
    name: "A350-900",
    category: "Widebody Jet",
    operators: "Rare Air Canada visitor (maintenance ferry/diversion)",
    service: "2015",
    fact1: "The A350 uses more carbon-fibre composite by weight than any other Airbus, giving it a lighter airframe and noticeably curved, downturned wingtips.",
    fact2: "Air Canada's A350s normally fly Canada's longest routes, so spotting one over Ottawa usually means a special charter, crew-training flight, or maintenance repositioning.",
    note: "",
  },
  {
    icao: "B739",
    manufacturer: "Boeing",
    name: "737-900ER",
    category: "Narrowbody Jet",
    operators: "WestJet",
    service: "2007",
    fact1: "The 737-900ER is the longest version of the 737 ever built, stretched so much that it needs extra emergency exits to meet evacuation rules.",
    fact2: "It became part of WestJet's fleet as the airline consolidated the former Sunwing leisure network into its own mainline operation in 2025.",
    note: "",
  },
  {
    icao: "B753",
    manufacturer: "Boeing",
    name: "757-300",
    category: "Narrowbody / Charter",
    operators: "Rare charter visitor",
    service: "1998",
    fact1: "The 757-300 is the longest single-aisle jet ever built by Boeing, roughly 7 metres longer than the standard 757-200.",
    fact2: "Very few were ever built, so seeing one at Ottawa usually means a specific charter operator on a one-off flight.",
    note: "",
  },
  {
    icao: "CN35",
    manufacturer: "Canadian North",
    name: "737-300 Combi",
    category: "Narrowbody / Passenger-Cargo Combi",
    operators: "Canadian North",
    service: "1985 (737-300)",
    fact1: "A \"Combi\" jet carries cargo pallets in the front of the cabin and passengers in the back behind a partition — a practical setup for flying both people and freight to Canada's North.",
    fact2: "Canadian North was formed by merging two historic northern carriers, First Air and Canadian North, in 2019.",
    note: "",
  },
  {
    icao: "SW4",
    manufacturer: "Fairchild (Swearingen)",
    name: "Metro/Merlin III",
    category: "Turboprop / Small Freighter",
    operators: "Small feeder-cargo operators",
    service: "1970",
    fact1: "The Metroliner's narrow, cylindrical fuselage earned it the nickname \"the Lead Sled\" among pilots for its dense, no-nonsense build.",
    fact2: "Small Metros have flown overnight parcel and bank-cheque runs into Ottawa for decades, often departing in the middle of the night.",
    note: "Nickname: \"Lead Sled\"",
  },
  {
    icao: "GL5T",
    manufacturer: "Bombardier",
    name: "Global 5000",
    category: "Business Jet",
    operators: "Corporate/charter operators",
    service: "2005",
    fact1: "The Global 5000 was developed alongside the Global Express as a shorter-range, lower-cost sibling, sharing most of the same wing and cockpit.",
    fact2: "It's a common choice for corporate flight departments needing nonstop Ottawa-to-Europe range without paying for the largest Global variant.",
    note: "",
  },
  {
    icao: "E55P",
    manufacturer: "Embraer",
    name: "Praetor 600",
    category: "Business Jet",
    operators: "Corporate/charter operators",
    service: "2019",
    fact1: "The Praetor 600 was the first mid-size business jet certified for \"fly-by-wire\" flight controls, technology normally reserved for larger jets.",
    fact2: "Embraer says its cabin altitude (effectively how much oxygen you feel at cruise) is among the lowest of any business jet in its class, reducing jet-lag fatigue.",
    note: "",
  },
  {
    icao: "C68A",
    manufacturer: "Cessna",
    name: "Citation Latitude",
    category: "Business Jet",
    operators: "Corporate/charter operators",
    service: "2015",
    fact1: "The Latitude has a flat cabin floor, unusual for a mid-size jet, making it feel noticeably roomier inside than its exterior size suggests.",
    fact2: "It quickly became one of Cessna's best-selling business jets after launch thanks to its combination of cabin comfort and short-runway capability.",
    note: "",
  },
  {
    icao: "PRM1",
    manufacturer: "Beechcraft",
    name: "Premier 1",
    category: "Business Jet",
    operators: "Owner-operator/charter",
    service: "2001",
    fact1: "The Premier 1 was one of the first business jets with a composite-material fuselage, built as a single-piece carbon-fibre barrel instead of riveted aluminum panels.",
    fact2: "It's designed to be flown single-pilot, keeping operating costs down for private owners.",
    note: "",
  },
  {
    icao: "PA34",
    manufacturer: "Piper",
    name: "PA-34 Seneca",
    category: "Trainer / GA (multi-engine)",
    operators: "Flight schools",
    service: "1971",
    fact1: "The Seneca is one of the most common aircraft Canadian pilots use to earn their multi-engine rating, the qualification needed to fly twin-engine aircraft.",
    fact2: "Its two engines are mounted close to the fuselage centerline, which makes it noticeably easier to control on one engine than many other light twins.",
    note: "",
  },
  {
    icao: "BE36",
    manufacturer: "Beechcraft",
    name: "Bonanza",
    category: "GA",
    operators: "Private owners",
    service: "1947",
    fact1: "The Bonanza has been in continuous production longer than any other airplane in history, with the same basic design still being built today.",
    fact2: "Early models had a distinctive V-shaped tail (the \"V-tail Bonanza\") that combined the rudder and elevator into just two control surfaces instead of three.",
    note: "",
  },
  {
    icao: "RV_",
    manufacturer: "Van's Aircraft",
    name: "RV Series",
    category: "Homebuilt / GA",
    operators: "Private owners (based at Rockcliffe, Carp, and other local airfields)",
    service: "1972",
    fact1: "Van's RV kits are the best-selling homebuilt aircraft design in the world — owners assemble them themselves, often over several years in a home garage.",
    fact2: "Despite being amateur-built, RVs are known for genuinely sporty, responsive handling that rivals purpose-built aerobatic aircraft.",
    note: "",
  },
  {
    icao: "VC25",
    manufacturer: "Boeing",
    name: "VC-25 (Air Force One)",
    category: "Government / Head-of-State Transport",
    operators: "Extremely rare — U.S. presidential visits only",
    service: "1990",
    fact1: "\"Air Force One\" isn't really an aircraft type — it's the call sign used by any U.S. Air Force aircraft carrying the President, though it almost always refers to the specially modified 747 VC-25.",
    fact2: "The VC-25 can be refuelled in mid-air, giving it, in theory, unlimited range for as long as the crew can stay awake.",
    note: "One of the rarest possible sightings at YOW — only during an official presidential visit",
  },
  {
    icao: "C32",
    manufacturer: "Boeing",
    name: "C-32 (757)",
    category: "Government / VIP Transport",
    operators: "Rare — U.S. government/VIP visits",
    service: "1998",
    fact1: "The C-32 is a militarized 757 used by the U.S. Air Force to fly the Vice President, First Lady, Secretary of State, and other senior officials — commonly seen supporting high-level visits to Ottawa.",
    fact2: "It carries advanced communications equipment so senior officials can stay in contact with Washington throughout the flight.",
    note: "",
  },
  {
    icao: "C5M",
    manufacturer: "Lockheed Martin",
    name: "C-5M Super Galaxy",
    category: "Military Transport",
    operators: "Rare — U.S. heavy-airlift support",
    service: "1969 (C-5); 2013 (M upgrade)",
    fact1: "The C-5 is one of the largest military aircraft in the world — its cargo hold is long enough to fit multiple helicopters or armoured vehicles nose to tail.",
    fact2: "Both the nose and tail of the aircraft open, letting crews drive vehicles straight through from one end to the other.",
    note: "",
  },
  {
    icao: "K35R",
    manufacturer: "Boeing",
    name: "KC-135 Stratotanker",
    category: "Military Tanker",
    operators: "Rare — U.S. escort/support aircraft",
    service: "1957",
    fact1: "The KC-135 shares its basic airframe design with the original Boeing 707 airliner and has remained in continuous U.S. Air Force service for well over 60 years.",
    fact2: "It refuels other aircraft in flight through a rigid, steerable \"flying boom\" operated by a crew member lying in the tail of the plane.",
    note: "",
  },
  {
    icao: "C40",
    manufacturer: "Boeing",
    name: "C-40 Clipper",
    category: "Government / VIP Transport",
    operators: "Rare — U.S. military/VIP visits",
    service: "2001",
    fact1: "The C-40 is a militarized Boeing 737-700 used by the U.S. Navy, Air Force, and Air National Guard to fly senior officials and congressional delegations.",
    fact2: "It's built on the same production line as Boeing's commercial 737 Next Generation jets, just with a stronger cargo floor and VIP interior.",
    note: "",
  },
];

const BY_ICAO = new Map(FACTS.map((f) => [f.icao, f]));

/**
 * Close relatives that share the same story. A320neo files as A20N but the
 * fun facts about the A320 still apply, and so on. Only for type codes that
 * do not have a row of their own.
 */
const ALIASES: Record<string, string> = {
  // A320 family
  A20N: "A320",
  A19N: "A319",
  // A220 family
  BCS1: "BCS3",
  // 737 MAX family
  B37M: "B38M",
  B39M: "B38M",
  // 777 family (both facts are 777-general)
  B772: "B77W",
  B773: "B77W",
  B77F: "B77W",
  // 787 family (carbon fibre + dimming windows apply to all)
  B789: "B788",
  B78X: "B788",
  // Embraer E-Jets
  E170: "E75L",
  E75S: "E75L",
  E195: "E190",
  // Dash 8 classic
  DH8B: "DH8C",
  // Bell 412 (feed reports the bare type code)
  B412: "B412EP",
  // Business jets / historic
  C56X: "C560",
  J60: "LJ60",
  T33: "T-33",
  GL6T: "GL7T",
};

export function factsFor(
  icaoType: string | null | undefined,
): AircraftFacts | null {
  if (!icaoType) return null;
  const key = icaoType.trim().toUpperCase();
  return BY_ICAO.get(key) ?? BY_ICAO.get(ALIASES[key] ?? "") ?? null;
}

/** Just the leading 4-digit year, e.g. "1994 (A321neo: 2017)" -> "1994". */
export function firstYear(service: string): string {
  return service.match(/\d{4}/)?.[0] ?? service;
}
