// Fun facts for the aircraft types that turn up around Ottawa (YOW).
// Source of record is data/ottawa_aircraft_fun_facts.xlsx; this file is
// generated from it. Keyed by ICAO type designator (Contact.enrichment.icaoType).

export interface AircraftFacts {
  /** ICAO type designator, e.g. "BCS3". */
  icao: string;
  manufacturer: string;
  /** Common name, e.g. "A220-300". */
  name: string;
  category: string;
  /** Operators seen with this type at YOW. */
  operators: string;
  /** Year entered service (may carry a parenthetical). */
  service: string;
  fact1: string;
  fact2: string;
  /** Nickname or spotting note; may be empty. */
  note: string;
}

const FACTS: AircraftFacts[] = [
  {
    icao: "A320",
    manufacturer: "Airbus",
    name: "A320",
    category: "Narrowbody Jet",
    operators: "Air Canada, Air Canada Rouge, WestJet, Sunwing",
    service: "1988",
    fact1: "The A320 was the first airliner ever built with full digital fly-by-wire controls, replacing mechanical cables with electronic signals.",
    fact2: "Over 11,000 A320-family jets have been built, making it one of the two best-selling airliner families in history (neck-and-neck with the 737).",
    note: "Family also includes the A319 and A321",
  },
  {
    icao: "A321",
    manufacturer: "Airbus",
    name: "A321 / A321neo",
    category: "Narrowbody Jet",
    operators: "Air Canada, WestJet",
    service: "1994 (A321neo: 2017)",
    fact1: "The A321neo (\"new engine option\") burns about 20% less fuel per seat than the original A321 thanks to new engines and wingtip sharklets.",
    fact2: "It's the longest member of the A320 family, stretched nearly 7 metres longer than the base A320.",
    note: "\"neo\" jets are easy to spot by their curved wingtip sharklets",
  },
  {
    icao: "A319",
    manufacturer: "Airbus",
    name: "A319",
    category: "Narrowbody Jet",
    operators: "Air Canada",
    service: "1996",
    fact1: "The A319 is the shortest of the classic A320 family and is popular for shorter, less-busy routes exactly like Ottawa's regional network.",
    fact2: "A319s were once used as executive VIP jets (ACJ319) for heads of state because their range with a light passenger load is huge.",
    note: "",
  },
  {
    icao: "BCS3",
    manufacturer: "Airbus",
    name: "A220-300",
    category: "Narrowbody Jet",
    operators: "Air Canada",
    service: "2016 (as CSeries)",
    fact1: "The A220 was originally designed and built entirely in Canada by Bombardier as the \"CSeries\" before Airbus took a majority stake in 2018.",
    fact2: "It's assembled in Mirabel, Quebec — meaning the plane flying over Ottawa may have been built just down the road.",
    note: "Started life as the Bombardier CS300",
  },
  {
    icao: "B738",
    manufacturer: "Boeing",
    name: "737-800",
    category: "Narrowbody Jet",
    operators: "WestJet, Sunwing, Air Canada",
    service: "1998",
    fact1: "The 737-800 is part of the best-selling \"Next Generation\" 737 family and remains the backbone of WestJet's entire fleet.",
    fact2: "A 737 has taken off or landed somewhere in the world roughly every 1.5 seconds on average — it's the most-produced Western jetliner ever.",
    note: "",
  },
  {
    icao: "B38M",
    manufacturer: "Boeing",
    name: "737 MAX 8",
    category: "Narrowbody Jet",
    operators: "WestJet, Flair Airlines",
    service: "2017",
    fact1: "The MAX's larger, more fuel-efficient engines sit further forward and higher on the wing than older 737s, giving it a distinctive look.",
    fact2: "Split-tip winglets (nicknamed \"scimitar\" winglets) reduce drag and are one of the easiest ways to tell a MAX apart from an older 737.",
    note: "",
  },
  {
    icao: "B788",
    manufacturer: "Boeing",
    name: "787-8 Dreamliner",
    category: "Widebody Jet",
    operators: "Air Canada",
    service: "2011",
    fact1: "The 787 was the first airliner built mostly from carbon-fibre composite instead of aluminum, letting cabins be pressurized to a lower, more comfortable altitude.",
    fact2: "Its windows are the largest of any commercial jet and dim electronically instead of using pull-down shades.",
    note: "Occasionally swapped onto Ottawa's transatlantic routes",
  },
  {
    icao: "B77W",
    manufacturer: "Boeing",
    name: "777-300ER",
    category: "Widebody Jet",
    operators: "Air France (seasonal), occasional Air Canada",
    service: "2004",
    fact1: "The 777's wingtips are so long and flexible that in testing they were bent upward more than 7 metres before the wing failed.",
    fact2: "It's the largest twin-engine jet ever built, and each of its GE90 engines is wide enough to fit a 737 fuselage through the intake.",
    note: "",
  },
  {
    icao: "B763",
    manufacturer: "Boeing",
    name: "767-300",
    category: "Widebody / Freighter",
    operators: "Cargojet, occasional Air Canada Rouge",
    service: "1986",
    fact1: "Retired passenger 767s are widely converted into freighters, and Cargojet's overnight network keeps several flying nightly out of Ottawa.",
    fact2: "The 767 was the first Boeing widebody designed from the outset for two-pilot crews instead of three.",
    note: "",
  },
  {
    icao: "B752",
    manufacturer: "Boeing",
    name: "757-200",
    category: "Narrowbody / Freighter",
    operators: "Cargojet, FedEx",
    service: "1983",
    fact1: "The 757 has the best power-to-weight ratio of any Boeing airliner, giving it famously strong takeoff performance out of shorter runways.",
    fact2: "Production ended in 2004, but so many were converted to freighters that it remains a staple of overnight cargo networks today.",
    note: "",
  },
  {
    icao: "E75L",
    manufacturer: "Embraer",
    name: "E175",
    category: "Regional Jet",
    operators: "Air Canada Express, United Express",
    service: "2005",
    fact1: "The E175 seats around 76 passengers and is the sweet spot size for feeder routes into a hub like Ottawa.",
    fact2: "Embraer's E-Jets were the first regional jets designed with a wider, more comfortable 2-2 cabin instead of the cramped 1-2 layout common on older regional jets.",
    note: "",
  },
  {
    icao: "E295",
    manufacturer: "Embraer",
    name: "E195-E2",
    category: "Narrowbody Jet",
    operators: "Porter Airlines",
    service: "2019",
    fact1: "The E195-E2 is Porter Airlines' primary jet for its expansion beyond Toronto Billy Bishop, and Porter was a global launch customer for the type.",
    fact2: "It's the quietest commercial jet in its class, certified under strict noise rules — handy for an airline that also flies out of a downtown airport.",
    note: "",
  },
  {
    icao: "CRJ9",
    manufacturer: "Bombardier",
    name: "CRJ900",
    category: "Regional Jet",
    operators: "Air Canada Express (Jazz)",
    service: "2003",
    fact1: "The CRJ family traces its roots to the Canadair Challenger business jet — the CRJ900's fuselage was literally stretched from a corporate jet design.",
    fact2: "Jazz Aviation, based in Halifax, operates the largest regional jet fleet in Canada, much of it feeding Air Canada's Ottawa flights.",
    note: "",
  },
  {
    icao: "CRJ2",
    manufacturer: "Bombardier",
    name: "CRJ200",
    category: "Regional Jet",
    operators: "Air Canada Express, PAL Airlines",
    service: "1992",
    fact1: "The CRJ200 was the aircraft that kicked off the modern regional-jet boom in North America in the 1990s.",
    fact2: "It cruises at the same altitude as many mainline jets, letting it fly above weather that keeps smaller turboprops grounded.",
    note: "",
  },
  {
    icao: "DH8D",
    manufacturer: "De Havilland Canada",
    name: "Dash 8-400 (Q400)",
    category: "Turboprop",
    operators: "Porter Airlines, Air Canada Express",
    service: "2000",
    fact1: "The Q400 is built in Toronto and is one of the fastest turboprops flying, cruising nearly as fast as some regional jets.",
    fact2: "Porter Airlines built its entire original identity around the Q400 and its signature tartan livery before adding jets in 2022.",
    note: "\"Q\" stood for \"quiet\" — active noise-cancelling technology in the cabin",
  },
  {
    icao: "DH8C",
    manufacturer: "De Havilland Canada",
    name: "Dash 8-300",
    category: "Turboprop",
    operators: "PAL Airlines, Air Inuit",
    service: "1989",
    fact1: "The Dash 8 family was originally developed by de Havilland Canada in Toronto and is still in production there today under De Havilland Canada.",
    fact2: "Its high wing and large propellers give it excellent short-field performance, useful for smaller northern and regional airports.",
    note: "",
  },
  {
    icao: "AT72",
    manufacturer: "ATR",
    name: "ATR 72",
    category: "Turboprop",
    operators: "Air Inuit, charter operators",
    service: "1988",
    fact1: "ATR is a joint venture between France's Airbus-linked Aerospatiale heritage and Italy's Leonardo, still building turboprops in Toulouse today.",
    fact2: "Its low wing keeps the cabin closer to the ground, so it doesn't need boarding stairs on shorter turnarounds.",
    note: "",
  },
  {
    icao: "DHC6",
    manufacturer: "De Havilland Canada",
    name: "DHC-6 Twin Otter",
    category: "Turboprop / Bush Plane",
    operators: "Air Inuit, survey/geophysics operators",
    service: "1965",
    fact1: "The Twin Otter can take off in under 300 metres and is still in production today (by Viking Air) because nothing else matches its rugged short-field ability.",
    fact2: "It's the aircraft of choice for Arctic and Antarctic research stations worldwide, including landing on skis and floats.",
    note: "",
  },
  {
    icao: "C208",
    manufacturer: "Cessna",
    name: "208 Caravan",
    category: "Utility Turboprop",
    operators: "Sanders Geophysics, small cargo/survey operators",
    service: "1984",
    fact1: "The Caravan was originally developed with FedEx as a launch customer for feeder cargo routes, and small Caravans still fly overnight parcels today.",
    fact2: "It can be fitted with wheels, skis, or floats, making it one of the most versatile single-engine aircraft ever built.",
    note: "",
  },
  {
    icao: "PC12",
    manufacturer: "Pilatus",
    name: "PC-12",
    category: "Turboprop",
    operators: "RCMP",
    service: "1994",
    fact1: "The PC-12 has a cabin large enough to convert into an air ambulance layout, and it's a favourite of police and medevac operators across Canada.",
    fact2: "Swiss-built Pilatus aircraft are known for exceptional short and rough-field performance, useful for reaching remote communities.",
    note: "",
  },
  {
    icao: "C560",
    manufacturer: "Cessna",
    name: "Citation V / Encore",
    category: "Business Jet",
    operators: "Transport Canada",
    service: "1989",
    fact1: "Transport Canada operates Citation jets for aviation inspections and calibrating the navigation aids at airports across the country.",
    fact2: "The Citation family is the best-selling business jet line in history, with well over 7,000 delivered.",
    note: "",
  },
  {
    icao: "GLEX",
    manufacturer: "Bombardier",
    name: "Global Express",
    category: "Business Jet",
    operators: "Corporate/charter operators (AirSprint and others)",
    service: "1998",
    fact1: "The Global Express was designed to fly nonstop from North America to Asia or Europe, and it set multiple round-the-world speed records after entering service.",
    fact2: "It was developed in Montreal using swept-wing technology borrowed from Bombardier's regional jet programs.",
    note: "",
  },
  {
    icao: "CL60",
    manufacturer: "Bombardier",
    name: "Challenger 604/605/650",
    category: "Business Jet",
    operators: "Corporate operators, RCAF (as CC-144)",
    service: "1996 (604)",
    fact1: "The Challenger was Bombardier's very first clean-sheet aircraft design, launched back in 1976, and its wide cabin cross-section was later reused for the CRJ regional jet.",
    fact2: "The RCAF's Challengers (CC-144) fly VIP transport for the Governor General, Prime Minister, and cabinet ministers out of Ottawa.",
    note: "",
  },
  {
    icao: "A310",
    manufacturer: "Airbus",
    name: "CC-150 Polaris (A310)",
    category: "Government / Strategic Transport",
    operators: "Royal Canadian Air Force",
    service: "1985 (A310); 1992 (RCAF conversion)",
    fact1: "Canada's five CC-150 Polaris jets are converted ex-airline A310s, some originally flown by Wardair and Canadian Airlines before joining the military.",
    fact2: "They serve as VIP transport for the Prime Minister and Governor General as well as strategic troop and cargo airlift, and can be fitted for air-to-air refuelling.",
    note: "Being phased out as the CC-330 Husky arrives",
  },
  {
    icao: "A332",
    manufacturer: "Airbus",
    name: "CC-330 Husky (A330 MRTT)",
    category: "Government / Tanker",
    operators: "Royal Canadian Air Force",
    service: "2025 (Canadian delivery)",
    fact1: "The CC-330 Husky is Canada's newest military aircraft type, a converted Airbus A330 multi-role tanker that can refuel fighter jets in mid-air.",
    fact2: "It's named \"Husky\" after the sled dog, continuing the RCAF tradition of naming heavy transport aircraft after Canadian working dogs.",
    note: "Replacing the CC-150 Polaris fleet",
  },
  {
    icao: "C130",
    manufacturer: "Lockheed Martin",
    name: "CC-130J Hercules",
    category: "Military Transport",
    operators: "Royal Canadian Air Force",
    service: "1999 (J model); 1960 (original Hercules)",
    fact1: "The Hercules has been in continuous production longer than any other military aircraft in history — over 65 years and counting.",
    fact2: "RCAF Hercules based out of the Ottawa area fly everything from Arctic resupply to search-and-rescue and disaster relief missions.",
    note: "",
  },
  {
    icao: "C17",
    manufacturer: "Boeing",
    name: "CC-177 Globemaster III",
    category: "Military Transport",
    operators: "Royal Canadian Air Force",
    service: "1995 (C-17); 2007 (RCAF)",
    fact1: "Canada's four Globemasters can carry a main battle tank and are among the largest aircraft to regularly use Ottawa's airport.",
    fact2: "The C-17 can land and take off from runways as short as about 1,000 metres, far shorter than a typical airliner needs.",
    note: "",
  },
  {
    icao: "ALJT",
    manufacturer: "Dassault-Dornier",
    name: "Alpha Jet",
    category: "Research / Chase Aircraft",
    operators: "National Research Council of Canada",
    service: "1978",
    fact1: "The NRC's Alpha Jets are used as chase planes to film and monitor experimental flight tests in real time from the air.",
    fact2: "The Alpha Jet was originally a joint French-German military trainer before a handful found second careers in Canadian flight research.",
    note: "",
  },
  {
    icao: "F20",
    manufacturer: "Dassault",
    name: "Falcon 20",
    category: "Research Aircraft",
    operators: "National Research Council of Canada",
    service: "1965",
    fact1: "NRC's Falcon 20 has flown atmospheric and icing research missions for decades, including flying directly into storm clouds to study ice buildup on wings.",
    fact2: "The Falcon 20 was Dassault's first business jet and helped launch the entire modern corporate jet industry.",
    note: "",
  },
  {
    icao: "CV58",
    manufacturer: "Convair",
    name: "CV-580",
    category: "Historic Research Aircraft",
    operators: "National Research Council of Canada",
    service: "1947 (as CV-240); 1960 (580 conversion)",
    fact1: "NRC's CV-580 has been used for decades of Canadian cloud-physics and icing research, flying into freezing rain to measure how ice forms on aircraft.",
    fact2: "It started life in the 1940s as a piston-engine Convair 240 airliner before being re-engined with turboprops in the 1950s-60s conversion program.",
    note: "",
  },
  {
    icao: "T-33",
    manufacturer: "Lockheed",
    name: "T-33 Shooting Star",
    category: "Historic Jet",
    operators: "National Research Council of Canada (heritage)",
    service: "1948",
    fact1: "The T-33 was North America's first mass-produced jet trainer, and Canadian-built versions (by Canadair) trained generations of RCAF pilots.",
    fact2: "NRC kept T-33s flying long after most air forces retired theirs, using them for decades of airborne research work.",
    note: "",
  },
  {
    icao: "E545",
    manufacturer: "Embraer",
    name: "Legacy 450",
    category: "Business Jet",
    operators: "AirSprint (fractional ownership)",
    service: "2015",
    fact1: "The Legacy 450 shares its wing design with Embraer's larger commercial jets, giving it an unusually smooth ride for its size.",
    fact2: "AirSprint, a Canadian fractional-ownership company, bases part of its private jet fleet in Ottawa for cross-Canada business travel.",
    note: "",
  },
  {
    icao: "C25B",
    manufacturer: "Cessna",
    name: "Citation CJ2/CJ3",
    category: "Business Jet",
    operators: "AirSprint and other charter operators",
    service: "2000 (CJ2)",
    fact1: "The CJ series is designed to be flown by a single pilot, keeping it popular with owner-operators and small charter fleets.",
    fact2: "It can use shorter runways than most jets its size, opening up smaller regional airports for private travel.",
    note: "",
  },
  {
    icao: "LJ60",
    manufacturer: "Bombardier (Learjet)",
    name: "Learjet 60",
    category: "Business Jet",
    operators: "Charter operators",
    service: "1993",
    fact1: "Learjet essentially invented the modern light business jet category in the 1960s, and \"Lear jet\" became a generic household term for any private jet.",
    fact2: "The Learjet 60 was one of the last all-new Learjet designs before Bombardier eventually wound the historic brand down in 2021.",
    note: "",
  },
];

const BY_ICAO = new Map(FACTS.map((f) => [f.icao, f]));

/**
 * Close relatives that share the same story. A320neo files as A20N but the
 * fun facts about the A320 still apply, and so on.
 */
const ALIASES: Record<string, string> = {
  // A320 family
  A20N: "A320",
  A19N: "A319",
  A21N: "A321",
  // A220 family
  BCS1: "BCS3",
  // 737 MAX family
  B37M: "B38M",
  B39M: "B38M",
  // 777 family (both facts are 777-general)
  B77L: "B77W",
  B772: "B77W",
  B773: "B77W",
  B77F: "B77W",
  // 787 family (carbon fibre + dimming windows apply to all)
  B789: "B788",
  B78X: "B788",
  // Embraer E-Jets
  E170: "E75L",
  E75S: "E75L",
  E190: "E295",
  E195: "E295",
  // CRJ family
  CRJ7: "CRJ9",
  // Dash 8 classic
  DH8A: "DH8C",
  DH8B: "DH8C",
  // Business jets / historic
  C56X: "C560",
  J60: "LJ60",
  T33: "T-33",
};

export function factsFor(
  icaoType: string | null | undefined,
): AircraftFacts | null {
  if (!icaoType) return null;
  const key = icaoType.trim().toUpperCase();
  return BY_ICAO.get(key) ?? BY_ICAO.get(ALIASES[key] ?? "") ?? null;
}
